name: Test RAM Monitor

on:
schedule:
    - cron: '0 1 * * *'
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run test.py
        run: python test.py
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
